#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# ------------------------------
# Step 1: Get the commit message (which is stored in a file by default)
# ------------------------------
path_to_commit_message_as_file=$1
original_message=`cat ${path_to_commit_message_as_file}`
echo original message is: $original_message


# -----------------------------------
# Step 2: Get the current branch name
# -----------------------------------
cur_branch_name=`git rev-parse --abbrev-ref head`

echo "[32m√[39m branch name passed the Pattern check! It is: ${cur_branch_name}"

# ---------------------------------
# Step 3: Check branch name pattern
# ---------------------------------

echo ""
echo "---------------------------------------------------"
echo " _               _            _ "
echo "| |   _   _  ___| | ___   _  | |    _____   _____ "
echo "| |  | | | |/ __| |/ / | | | | |   / _ \ \ / / _ \ "
echo "| |__| |_| | (__|   <| |_| | | |__| (_) \ V /  __/ "
echo "|_____\__,_|\___|_|\_\\\__, | |_____\___/ \_/ \___| "
echo "                      |___/"
echo "---------------------------------------------------"

echo ""
echo "---------------------"
echo "Step 1: npm run lint"
echo "--------------------"
echo "Command: eslint -c ./.eslintrc.json \"./lib/**/*.js\""
echo "running lint..."

pnpm run lint

echo "[32m√[39m lint check ran successfully! Everything seems ok."


echo ""
echo "--------------------"
echo "Step 2: npm run test"
echo "--------------------"
echo "Command: node --test"
echo "running tests..."

npm test

echo "[32m√[39m e2e tests & Unit Tests ran successfully! All tests PASSED!"
echo "[32m√[39m Changes have been commited successfully!"


echo ""
echo "----------------------"
echo "Step 3: npm run format"
echo "----------------------"
echo "Command: npm test"
echo "running formatter..."

npm run format

echo "[32m√[39m Formatter ran successfully!"

echo ""
echo "  ____                              _  "
echo " / ___| _   _  ___ ___ ___  ___ ___| | "
echo " \___ \| | | |/ __/ __/ _ \/ __/ __| | "
echo "  ___) | |_| | (_| (_|  __/\__ \__ \_| "
echo " |____/ \__,_|\___\___\___||___/___(_) "
echo ""

echo "    _    _ _      _              _           ____   _    ____ ____  _____ ____  _   "
echo "   / \  | | |   _| |_ ___  ___ _| |_ ___    |  _ \ / \  / ___/ ___|| ____|  _ \| |  "
echo "  / _ \ | | |  |_  __/ _ \/ __|_   _/ __|   | |_) / _ \ \___ \___ \|  _| | | | | |  "
echo " / ___ \| | |    | ||  __/\__ \ | |_\__ \   |  __/ ___ \ ___) |__) | |___| |_| |_|  "
echo "/_/   \_\_|_|     \__\___||___/ \___|___/   |_| /_/   \_\____/____/|_____|____/(_)  "
echo ""

echo "[32m√[39m Changes have been commited successfully!"
