name: Publish

on:
  push:
    branches:
      - 'master'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout
      - uses: actions/checkout@v3

      # Step 2: Set up pnpm
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      # Step 3: Set up node
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'pnpm'

      # Step 3: Run pnpm install
      - run: pnpm install --frozen-lockfile

      # Step 4: Run pnpm lint & build
      - run: pnpm run lint && pnpm run build

      # Step 5: Run publish
      - name: 'Create Release Pull Request or Publish'
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
